### ISSUE TITLE
Missing a date

### ISSUE THREAD

**Issue by jcorbs** [NathanBeeler/DataParsingExercise#2]
The file contains four dates, you have three. The remaining one is 01310133, why did your code not find it?

**Comment by NathanBeeler** [comment]
The code was finding that date before I added the month offset logic. Then it ignored it because Feb 31st isn't a valid date.

**Comment by jcorbs** [comment]
That's not February 31st though, that's January 31st!

**Comment by NathanBeeler** [comment]
Wouldn't January 31st be 00310133? Or have I misunderstood the zero-based month idea?

**Comment by jcorbs** [comment]
Ah, I see. This is a new exercise that we created for the position so there are a few misunderstandings (and two typos on the doc you got). It was intended to be MM, not necessarily 0 based, though that is curious idea! This looks good, thanks.
